---
# apply with: ansible-galaxy install -r requirements.yaml
# see: https://docs.ansible.com/ansible/devel/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file
# see: https://galaxy.ansible.com/docs/using/installing.html#installing-multiple-roles-from-a-file

collections:
  - name: community.general

roles:
  - name: gantsign.oh-my-zsh
