- name: Extend the logical volume to take all remaining space of the PVs and resize the underlying filesystem
  hosts: "*"
  become: yes
  tasks:
      ## Install Ansible Galaxy community collection first. "ansible-galaxy collection install community.general"
      ## https://galaxy.ansible.com/community/general
      community.general.lvol:
        vg: ubuntu-vg
        lv: ubuntu-lv
        size: +100%FREE
        resizefs: true

- name: Set timezone and configure timesyncd
  hosts: "*"
  become: yes
  tasks:
  - name: set timezone
    shell: timedatectl set-timezone Pacific/Auckland

  - name: Make sure timesyncd is stopped
    systemd:
      name: systemd-timesyncd.service
      state: stopped

  - name: Make sure timesyncd is started
    systemd:
      name: systemd-timesyncd.service
      state: started

- name: install latest zsh on all hosts
  hosts: "*"
  tasks:
    - name: install zsh
      apt:
        name: zsh
        state: present
        update_cache: true
      become: true    
- name: Update apps
  hosts: "*"
  become: yes
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'
        
- name: Install oh-my-zsh
  hosts: "*"
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: master ## Username of the account you'd like to install Oh-My-Zsh to. Use "ansible-galaxy install gantsign.oh-my-zsh" first.
                         ## https://galaxy.ansible.com/gantsign/oh-my-zsh  
- hosts: "*"
  become: yes
  tasks:
    - name: Reboot a slow machine that might have lots of updates to apply
      reboot:
        reboot_timeout: 3600